name: "Pymodeller Drift"
description: "Check drift between YAML spec and generated code"


runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        enable-cache: true
        python-version: "3.13"

    - name: Install pymodeller
      run: uv tool install pymodeller --python 3.13
      shell: bash

    - name: Run drift check
      run: pymodeller drift
      shell: bash
