sonar.projectKey=pymodeller_PyModeller
sonar.qualitygate.wait=true

sonar.sources=src

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.flake8.reportPaths=flake8.txt

sonar.exclusions=**/assets/**,**/tests/**,**/docs/**,**/docker/**,**/static/**

sonar.coverage.exclusions=**/tests/**,**/docs/**
