sonar.organization=pymodeller
sonar.projectKey=pymodeller_PyModeller
sonar.qualitygate.wait=true

sonar.sources=src

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/assets/**,**/tests/**,**/docs/**,**/docker/**,**/static/**

sonar.coverage.exclusions=**/tests/**,**/docs/**
