name: Master Pipeline

on:
  push:
    branches: [ main, develop ]
    tags-ignore: [ 'v*' ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - 'feature/*'
  workflow_dispatch:

jobs:
  pre-commit:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    uses: ./.github/workflows/pre-commit.yaml

  test:
    needs: pre-commit
    uses: ./.github/workflows/test.yaml
    secrets:
      PR_TOKEN_USER: ${{ secrets.PR_TOKEN }}

  sonar:
    needs: test
    uses: ./.github/workflows/sonarqube.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  approve-release:
    needs: sonar
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')) ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    environment: release
    steps:
      - run: echo "Release approved by user"

  release:
    needs: approve-release
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/semantic-release.yaml
    secrets:
      PR_TOKEN_USER: ${{ secrets.PR_TOKEN }}

  docs:
    needs: [test, release]
    if: |
      always() &&
      (needs.release.result == 'success') && needs.test.result == 'success' &&
      github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/docs.yaml

  publish:
    name: 🚀 Publish to PyPI
    needs: [ release ]
    if: |
      always() &&
      needs.release.result == 'success' &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest changes (from release job)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
        shell: bash

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b

  # 5. Docker (Solo tras un nuevo Release exitoso)
  # docker:
  #   needs: [test, release]
  #   if: |
  #     always() && github.event_name == 'push' &&
  #     (github.ref == 'refs/heads/main' || needs.release.result == 'success')
  #   permissions:
  #     packages: write
  #     contents: read
  #   uses: ./.github/workflows/docker-publish.yaml
  #   secrets: inherit
