name: Master Pipeline

on:
  push:
    branches: [ main, develop ]
    tags-ignore: [ 'v*' ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - 'feature/*'
  workflow_dispatch:

jobs:
  # 1. Pre-commit (Calidad de código rápida)
  call-pre-commit:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    uses: ./.github/workflows/pre-commit.yaml

  # 2. Tests (Lógica y cobertura)
  call-test:
    needs: call-pre-commit
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  # 3. Semantic Release (Solo en PUSH a main)
  call-release:
    needs: call-test
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')) ||
      (github.event_name == 'workflow_dispatch')
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    uses: ./.github/workflows/semantic-release.yaml
    secrets: inherit

  # 4. Documentación y Badges
  call-docs:
    needs: [call-test, call-release]
    if: |
      always() &&
      (needs.call-release.result == 'success') && needs.call-test.result == 'success'
    permissions:
      contents: write
    uses: ./.github/workflows/docs.yaml

  # call-publish:
  #   needs: [call-release, call-docs]
  #   if: |
  #     always() &&
  #     needs.call-release.result == 'success' &&
  #     github.ref == 'refs/heads/main'
  #   permissions:
  #     id-token: write  # Requerido para OIDC (Trusted Publishers)
  #     contents: read
  #   uses: ./.github/workflows/publish.yml  # Asegúrate de que la extensión sea .yml o .yaml según tu archivo
  #   secrets: inherit

  publish:
    name: 🚀 Publish to PyPI
    needs: [ call-release ]
    # Solo si el release fue bien y estamos en main
    if: |
      always() &&
      needs.call-release.result == 'success' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    # 1. Definimos el entorno
    environment: release

    # 2. Permisos para OIDC
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  # 5. Docker (Solo tras un nuevo Release exitoso)
  # call-docker:
  #   needs: [call-test, call-release]
  #   if: |
  #     always() && github.event_name == 'push' &&
  #     (github.ref == 'refs/heads/main' || needs.call-release.result == 'success')
  #   permissions:
  #     packages: write
  #     contents: read
  #   uses: ./.github/workflows/docker-publish.yaml
  #   secrets: inherit
